### ISSUE TITLE
function for simulate alpha opacity

### ISSUE THREAD

**Issue by francescoagati** [fponticelli/thx.color#25]
```
class ColorTools {
  public inline static function withAlphaEmulated(color:thx.color.Rgbx,background:thx.color.Rgb,alpha:Float) {
    var red =  Std.int((1 - alpha) * background.red + alpha * color.red);
    var green =  Std.int((1 - alpha) * background.green + alpha * color.green);
    var blue = Std.int((1 - alpha) * background.blue + alpha * color.blue);
    trace(red,green,blue);
    return ('rgb($red,$green,$blue)':thx.color.Rgb);
  }
}
```

based on http://yolijn.com/convert-rgba-to-rgb

**Comment by fponticelli** [comment]
Interesting idea. Why not adding `combineColors` directly to `Rgba` and `Rgbxa`?

**Comment by fponticelli** [comment]
If we add `combineColors` your use case would become:

```haxe
color.withAlpha(0.5).combineColor(otherColor); // changed `combineColors` to `combineColor`
```

**Comment by francescoagati** [comment]
and with combineColor i can after convert rgba to normal rgb?

2015-07-13 17:09 GMT+02:00 Franco Ponticelli <notifications@github.com>:

**Comment by fponticelli** [comment]
You can always do that (implicitly or through `.toRgb`) but since the alpha info is lost in `combineColor` I guess the output should be directly `Rgb` or `Rgbx`. I can add this later today or I will be glad to accept a PR.

**Comment by francescoagati** [comment]
ok i prepare a pull request

2015-07-13 17:15 GMT+02:00 Franco Ponticelli <notifications@github.com>:

**Comment by fponticelli** [comment]
;)

**Comment by fponticelli** [comment]
Implemented, thank you for the suggestion.

**Comment by francescoagati** [comment]
:+1:
